### ISSUE TITLE
SDK中的boost1.68与本地程序中的boost1.58冲突

### ISSUE THREAD

**Issue by liming0791** [INDEMIND/SDK-Linux#3]
如题，是否有解决方案。

**Comment by webbery** [comment]
你好，
可以尝试在本地编译boost1.68。

**Comment by webbery** [comment]
我们在使用ROS kinetic的时候并没有发现冲突。可以提供具体的ROS kinetic安装命令吗？

**Comment by MerlotQ** [comment]
boost 版本问题最头疼了 可以在sdk里自带一个boost库 不然这种依赖特定boost库的硬件做的真是很一般 没有小觅智能那款好

**Comment by webbery** [comment]
目前新提交的版本已经移除了boost filesystem、system库的冲突问题
