### ISSUE TITLE
 undefined symbol: _ZN2cv3Mat20updateContinuityFlagEv

### ISSUE THREAD

**Issue by VinchinYang** [INDEMIND/SDK-Linux#8]
出现如下错误：
SDK-Linux-master/demo/../lib/1604/libindem.so: undefined symbol: _ZN2cv3Mat20updateContinuityFlagEv

**Comment by webbery** [comment]
OpenCV需要链接我们提供的版本，在bin目录下。系统自带的版本可能有兼容性问题
